<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>false</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3" />
    <PackageVersion Include="coverlet.collector" Version="10.0.1" />
    <PackageVersion Include="EvilBaschdi.About.Avalonia" Version="2026.7.29.16" />
    <PackageVersion Include="EvilBaschdi.About.Terminal" Version="2026.7.29.16" />
    <PackageVersion Include="EvilBaschdi.Core" Version="2026.6.18.15" />
    <PackageVersion Include="EvilBaschdi.Core.Avalonia" Version="2026.8.3.15" />
    <PackageVersion Include="EvilBaschdi.Core.DependencyInjection" Version="2026.8.11.17" />
    <PackageVersion Include="EvilBaschdi.Core.Settings" Version="2026.8.11.18" />
    <PackageVersion Include="EvilBaschdi.Testing" Version="2026.8.15.6" />
    <PackageVersion Include="EvilBaschdi.Testing.Avalonia" Version="2026.8.3.15" />
    <PackageVersion Include="FluentAssertions.Analyzers" Version="0.34.1" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageVersion Include="NSubstitute.Analyzers.CSharp" Version="1.0.17" />
    <PackageVersion Include="Spectre.Console" Version="0.57.2" />
    <PackageVersion Include="System.DirectoryServices" Version="10.0.11" />
    <PackageVersion Include="System.DirectoryServices.AccountManagement" Version="10.0.11" />
    <PackageVersion Include="xunit.v3" Version="4.0.0" />
    <PackageVersion Include="xunit.analyzers" Version="2.0.0" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="4.0.0" />
  </ItemGroup>
</Project>